[changelog]
header = """
# ğŸ“‹ Ğ˜ÑÑ‚Ğ¾Ñ€Ğ¸Ñ Ğ¸Ğ·Ğ¼ĞµĞ½ĞµĞ½Ğ¸Ğ¹
"""
body = """
{% if version %}## {{ version }}{% else %}## Ğ’ Ñ€Ğ°Ğ·Ñ€Ğ°Ğ±Ğ¾Ñ‚ĞºĞµ{% endif %} - {{ timestamp | date(format="%Y-%m-%d") }}
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | striptags | trim | upper_first }}
{% for commit in commits %}
- {% if commit.scope %}**{{ commit.scope }}:** {% endif %}{{ commit.message | upper_first }} ({{ commit.id | truncate(length=7, end="") }})
{% endfor %}
{% endfor %}
"""
trim = true
footer = ""

[git]
conventional_commits = true
filter_unconventional = true
split_commits = false
commit_parsers = [
    { message = "^feat", group = "<!-- 0 -->âœ¨ ĞĞ¾Ğ²Ñ‹Ğµ Ğ²Ğ¾Ğ·Ğ¼Ğ¾Ğ¶Ğ½Ğ¾ÑÑ‚Ğ¸" },
    { message = "^fix", group = "<!-- 1 -->ğŸ› Ğ˜ÑĞ¿Ñ€Ğ°Ğ²Ğ»ĞµĞ½Ğ¸Ñ Ğ¾ÑˆĞ¸Ğ±Ğ¾Ğº" },
    { message = "^refactor", group = "<!-- 2 -->â™»ï¸ Ğ ĞµÑ„Ğ°ĞºÑ‚Ğ¾Ñ€Ğ¸Ğ½Ğ³" },
    { message = "^perf", group = "<!-- 3 -->âš¡ ĞŸÑ€Ğ¾Ğ¸Ğ·Ğ²Ğ¾Ğ´Ğ¸Ñ‚ĞµĞ»ÑŒĞ½Ğ¾ÑÑ‚ÑŒ" },
    { message = "^build", group = "<!-- 4 -->ğŸ›  Ğ¡Ğ±Ğ¾Ñ€ĞºĞ° Ğ¸ Ğ·Ğ°Ğ²Ğ¸ÑĞ¸Ğ¼Ğ¾ÑÑ‚Ğ¸" },
    { message = "^ci", group = "<!-- 5 -->ğŸ‘· CI/CD" },
    { message = "^docs", group = "<!-- 6 -->ğŸ“š Ğ”Ğ¾ĞºÑƒĞ¼ĞµĞ½Ñ‚Ğ°Ñ†Ğ¸Ñ" },
    { message = "^style", group = "<!-- 7 -->ğŸ¨ Ğ¡Ñ‚Ğ¸Ğ»ÑŒ ĞºĞ¾Ğ´Ğ°" },
    { message = "^test", group = "<!-- 8 -->ğŸ§ª Ğ¢ĞµÑÑ‚Ñ‹" },
    { message = "^chore", group = "<!-- 9 -->ğŸ”§ ĞŸÑ€Ğ¾Ñ‡ĞµĞµ" },
    { message = "^revert", group = "<!-- 10 -->âª ĞÑ‚ĞºĞ°Ñ‚ Ğ¸Ğ·Ğ¼ĞµĞ½ĞµĞ½Ğ¸Ğ¹" },
]
protect_breaking_commits = false
filter_commits = false
tag_pattern = "v[0-9].*"
skip_tags = ""
ignore_tags = ""
topo_order = false
sort_commits = "oldest"
